apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - server/api-global-ip.yaml
  - server/api-ingress.yaml
  - client/client-global-ip.yaml
  - client/client-ingress.yaml
patchesStrategicMerge:
  - postgres/user-credentials.yaml
  - server/postgres-credentials.yaml
  - server/node-port-service.yaml
  - client/node-port-service.yaml
