FROM node:14.18-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --only=development

# https://github.com/isaacs/rimraf/issues/212
RUN npm install rimraf

COPY . .

RUN npm run build

# -------------------

FROM node:14.18-alpine

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --only=production

COPY . .

COPY --from=build /usr/src/app/dist ./dist

CMD ["node", "dist/src/main"]
