apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubedev-postgres-pv-claim
  labels:
    app: kubedev-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
