apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubedev-postgres-pv
  labels:
    type: local
    app: kubedev-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /xxx
