apiVersion: v1
kind: Service
metadata:
  name: neverrekt-postgres-service
  labels:
    app: neverrekt-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: neverrekt-postgres
